Assessment Test 2: NumPy

Section A – Array Creation

In [1]:
import numpy as np

In [2]:
#Create an array from 1 to 20.

arr=np.arange(1,21)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [3]:
#Create an array of zeros (3×3).
np.zeros((3,3))



array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [4]:
#Create an identity matrix (4×4).

arr2=np.identity(4)
print(arr2)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [5]:
#Create an array of even numbers from 2 to 20.
arr3=np.arange(2,21,2)
print(arr3)

[ 2  4  6  8 10 12 14 16 18 20]


Section B – Reshape & Shape

In [6]:
#Create an array from 1 to 24.
arr4=np.arange(1,25)
print(arr4)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [7]:
#Reshape it into:
print(arr4.reshape(4,6))

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [8]:
print(arr4.reshape(6,4))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


In [9]:
print(arr4.reshape(2,12))

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [10]:
#Print the shape.
#Print the number of dimensions.
#Print the data type.

print(arr4.shape)

(24,)


In [11]:
print(arr4.size)

24


In [12]:
print(arr4.ndim)

1


Section C – Indexing & Slicing

In [13]:
a = np.arange(1,26)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]


In [14]:
b=a.reshape(5,5)
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [15]:
b[0,:]

array([1, 2, 3, 4, 5])

In [16]:
b[-1,:]

array([21, 22, 23, 24, 25])

In [17]:
b[:,0]

array([ 1,  6, 11, 16, 21])

In [18]:
b[:,-1]

array([ 5, 10, 15, 20, 25])

In [19]:
b[2,2]

np.int64(13)

In [20]:
b[0:3,0:3]

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13]])

In [21]:
b[3:5,3:5]

array([[19, 20],
       [24, 25]])

Section D – Mathematical Operations

In [22]:
c = np.array([2,4,6,8,10])
print(c)

[ 2  4  6  8 10]


In [23]:
print(c.mean())

6.0


In [24]:
print(c.max())

10


In [25]:
print(c.min())

2


In [26]:
print(c.sum())

30


In [27]:
print(c**2)

[  4  16  36  64 100]


In [28]:
print(np.sqrt(c))

[1.41421356 2.         2.44948974 2.82842712 3.16227766]


In [29]:
print(c*5)

[10 20 30 40 50]


Section E – Practical

In [30]:
marks = np.array([
[65,72,81],
[55,90,78],
[88,69,91]
])
print(marks)

[[65 72 81]
 [55 90 78]
 [88 69 91]]


In [31]:
#Total marks of all students.
marks.sum()
print(f"Total marks of all students are {marks.sum()}")

Total marks of all students are 689


In [32]:
marks.mean()
print(f"Average marks of all students are {marks.mean()}")

Average marks of all students are 76.55555555555556


In [33]:
marks.max()
print(f"Highest marks are {marks.max()}")

Highest marks are 91


In [34]:
marks.min()
print(f"Lowest marks are {marks.min()}")

Lowest marks are 55


In [35]:
print(f" Marks of second student are {marks[1,:]}")

 Marks of second student are [55 90 78]


In [36]:
print(f" Marks in third subject are {marks[:,2]}")

 Marks in third subject are [81 78 91]


In [37]:
print(marks+5)

[[70 77 86]
 [60 95 83]
 [93 74 96]]


In [38]:
print(marks.T)

[[65 55 88]
 [72 90 69]
 [81 78 91]]


In [39]:
print(marks.flatten())

[65 72 81 55 90 78 88 69 91]


In [40]:
print(marks.shape)

(3, 3)
