In [4]:
import numpy as np
arr=np.array([[10,20,30],
            [40,50,60]])
print(arr)
print(arr[0,0])
print(arr[0,2])
print(arr[1,0])
print(arr[1,2])

[[10 20 30]
 [40 50 60]]
10
30
40
60


In [6]:
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

2
(2, 3)
6
int64


In [7]:
print(arr[:,1])

print(arr[0,:])

print(arr[1,:])

print(arr[:,0])

print(arr[:,2])

[20 50]
[10 20 30]
[40 50 60]
[10 40]
[30 60]


In [8]:
a=np.arange(1,13)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [9]:
b = a.reshape(3,4)

print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [11]:
c=a.reshape(4,3)
print(c)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [12]:
print(b.flatten())

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [13]:
print(b.T)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [14]:
print(b.ravel())

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [17]:
#exercise1-2

arr1=np.array([[5,10,15],
             [20,25,30]])
print(arr1)
print(arr1.ndim)
print(arr1.size)
print(arr1.shape)
print(arr1.dtype)


[[ 5 10 15]
 [20 25 30]]
2
6
(2, 3)
int64


In [19]:
#exercise3

print(arr1[0,:])
print(arr1[1,:])
print(arr1[:,0])
print(arr1[:,1])
print(arr1[:,2])

[ 5 10 15]
[20 25 30]
[ 5 20]
[10 25]
[15 30]


In [23]:
#exercise4

d=np.arange(1,17)
print(d)

print(d.reshape(4,4))


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [24]:
print(d.reshape(2,8))

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]


In [25]:
print(d.reshape(8,2))


[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]]


In [26]:
#exercise6
print(arr1.T)

[[ 5 20]
 [10 25]
 [15 30]]


In [28]:
#exercise7
print(arr1.ravel())

[ 5 10 15 20 25 30]


In [30]:
#exercise8
i=np.identity(3)
print(i)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [31]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [33]:
#Mini project
marks = np.array([
    [80,75,90,85],
    [70,88,78,82],
    [95,91,89,93],
    [60,72,68,70],
    [85,80,84,88]
])

print(marks)
print(marks.shape)
print(marks[2,:]) #marks of third student
print(marks[:,1]) #marks in second subject


[[80 75 90 85]
 [70 88 78 82]
 [95 91 89 93]
 [60 72 68 70]
 [85 80 84 88]]
(5, 4)
[95 91 89 93]
[75 88 91 72 80]


In [35]:
marks.max()

np.int64(95)

In [36]:
marks.min()

np.int64(60)

In [37]:
marks.mean()

np.float64(81.15)

In [38]:
marks.mean(axis=0)

array([78. , 81.2, 81.8, 83.6])

In [39]:
marks.mean(axis=1)

array([82.5 , 79.5 , 92.  , 67.5 , 84.25])

In [40]:
marks.sum(axis=1) #third student has highest total marks

array([330, 318, 368, 270, 337])