In [1]:
import numpy as np
import random

arr = np.array([10, 25, 30, 45, 50, 65, 70])

print(arr>30)

[False False False  True  True  True  True]


In [2]:

print(arr[arr>30])

[45 50 65 70]


In [3]:
print(arr < 50)
print(arr[arr < 50])

print(arr % 2 == 0)
print(arr[arr % 2 == 0])

[ True  True  True  True False False False]
[10 25 30 45]
[ True False  True False  True False  True]
[10 30 50 70]


In [4]:
marks = np.array([78, 85, 90, 67, 88, 95, 73])

print(f"total marks is{marks.sum()}.")
print(f"min marks is {marks.min()}.")
print(f"max marks is {marks.max()}.")
print(f"average marks is {marks.mean()}.")
print(f"Standard deviation is {marks.std()}.")
print(f"variance of marks is {marks.var()}.")
np.median(marks)


total marks is576.
min marks is 67.
max marks is 95.
average marks is 82.28571428571429.
Standard deviation is 9.253791280400941.
variance of marks is 85.6326530612245.


np.float64(85.0)

In [5]:
np.random.rand(5)

array([0.26753216, 0.69197682, 0.73033687, 0.02080392, 0.564204  ])

In [6]:
np.random.randint(1,100,10)

array([77, 40, 36,  2, 81, 56, 61, 54, 80, 23], dtype=int32)

In [7]:
np.random.randn(5)

array([ 0.50802601,  0.40833916,  0.59038282,  0.84019946, -1.76472546])

In [8]:
random.seed(5)
print(random.sample(range(1, 50), 6))

[40, 17, 23, 45, 42, 34]


In [9]:
a = list(range(10))
random.seed(10)
random.shuffle(a)
print(a)


[5, 2, 7, 1, 8, 4, 3, 6, 0, 9]


In [10]:
a = [1, 2, 3, 4, 5, 6]
print(random.choice(a))

s = "geeks"
print(random.choice(s))

tup = (1, 2, 3, 4, 5)
print(random.choice(tup))

3
e
1


In [11]:
from random import sample
a = [1, 2, 3, 4, 5]
print(sample(a,3))

b = (4, 5, 6, 7, 8)
print(sample(b,3))

c = "45678"
print(sample(c,3))

[5, 4, 2]
[4, 5, 6]
['6', '4', '5']


In [12]:
a = [1, 2, 3, 4, 5]

random.shuffle(a)
print("After shuffle : ")
print(a)

random.shuffle(a)
print("\nSecond shuffle : ")
print(a)

After shuffle : 
[1, 4, 5, 3, 2]

Second shuffle : 
[3, 1, 4, 2, 5]


In [13]:
arr = np.array([45,12,78,9,34,67])
np.sort(arr)

array([ 9, 12, 34, 45, 67, 78])

In [14]:
arr[::-1]

array([67, 34,  9, 78, 12, 45])

In [15]:
np.argsort(arr)

array([3, 1, 4, 0, 5, 2])

In [16]:
#Real Mini Project

sales = np.array([
    [120,150,130,140],
    [200,210,190,220],
    [160,170,180,175]
])
print(sales)

[[120 150 130 140]
 [200 210 190 220]
 [160 170 180 175]]


In [17]:
#1 total sales
print(f"Total sales = {sales.sum()}.")

Total sales = 2045.


In [18]:
#2 average sales
print(f"Average sales = {sales.mean()}.")

Average sales = 170.41666666666666.


In [19]:
#3 max sales
print(f"Max sale = {sales.max()}.")

Max sale = 220.


In [20]:
#4 min sales
print(f"Min sale = {sales.min()}.")

Min sale = 120.


In [21]:
#5 total sales of each salesperson (axis=1)
sales.sum(axis=1)

array([540, 820, 685])

In [22]:
#6 Average sales of each month (axis=0)
sales.mean(axis=0)

array([160.        , 176.66666667, 166.66666667, 178.33333333])

In [38]:
#7 Which salesperson sold the most?
sales.sum(axis=1) #second sales person has max sales 

array([540, 820, 685])

In [24]:
#8 Which month had the highest average sales?
sales.mean(axis=0)  #4th month has highest aeverage sales.

array([160.        , 176.66666667, 166.66666667, 178.33333333])

In [25]:
#Challenge 1
arr = np.arange(1,26)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]


In [26]:
arr1=arr.reshape(5,5)
print(arr1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [27]:
print(arr1[0,:]) # first row

[1 2 3 4 5]


In [28]:
print(arr1[-1,:]) #last row

[21 22 23 24 25]


In [29]:
print(arr1[:,0]) #first column

[ 1  6 11 16 21]


In [30]:
print(arr1[:,-1]) #last column

[ 5 10 15 20 25]


In [39]:
print(arr1[2,2]) #center element

13


In [32]:
print(arr1[0:3,0:3]) #Top-left 3×3 block

[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]]


In [33]:
print(arr1[3:5,3:5]) #Bottom-right 2×2 block

[[19 20]
 [24 25]]


In [34]:
# challenge2
marks = np.array([
    [80,75,90,85],
    [70,88,78,82],
    [95,91,89,94]
]) 
print(marks)

[[80 75 90 85]
 [70 88 78 82]
 [95 91 89 94]]


In [35]:
#Which student scored the highest total?
marks.sum(axis=1) #last one has the highest total marks.

array([330, 318, 369])

In [36]:
#Which subject has the highest average?
marks.mean(axis=0) #last one subject has the highest average.

array([81.66666667, 84.66666667, 85.66666667, 87.        ])

In [37]:
#Which student scored the highest in Subject 2?
marks.max(axis=0) #highest marks in subject 2 is 91(in last row) for last one student.

array([95, 91, 90, 94])