In [15]:
import numpy as np
arr=np.array([10,20,30,40,50])
print(arr)
print(arr[0])
print(arr[2])
print(arr[-1])
print(arr[1:4])
print(arr[:3])
print(arr[2:])


[10 20 30 40 50]
10
30
50
[20 30 40]
[10 20 30]
[30 40 50]


In [3]:
print(arr.ndim)

1


In [4]:
print(arr.dtype)

int64


In [5]:
print(arr.size)

5


In [6]:
print(arr.shape)

(5,)


In [9]:
print(np.zeros(5))

[0. 0. 0. 0. 0.]


In [10]:
print(np.ones(5))

[1. 1. 1. 1. 1.]


In [12]:
print(np.arange(1,11))

[ 1  2  3  4  5  6  7  8  9 10]


In [13]:
print(np.linspace(1,100,5))

[  1.    25.75  50.5   75.25 100.  ]


In [16]:
a = np.array([1,2,3])

b = np.array([4,5,6])

print(a+b)

print(a-b)

print(a*b)

print(a/2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.5 1.  1.5]


In [17]:
#exercise1

arr1=np.array([5,10,15,20,25])
print(arr1)

[ 5 10 15 20 25]


In [18]:
#exercise2

print(arr1.ndim)
print(arr1.shape)
print(arr1.size)
print(arr1.dtype)

1
(5,)
5
int64


In [19]:
#exercise3-6

print(np.arange(10,51,5))
print(np.linspace(100,500,9))
print(np.zeros(8))
print(np.ones(10))

[10 15 20 25 30 35 40 45 50]
[100. 150. 200. 250. 300. 350. 400. 450. 500.]
[0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [23]:
#exercise7-10
print(arr1[2])
print(arr1[-1])
print(arr1[:4])
print(arr1[2:])


15
25
[ 5 10 15 20]
[15 20 25]


In [24]:
#exercise8

A = np.array([10,20,30])

B = np.array([2,4,6])

print(A+B)
print(A-B)
print(A*B)
print(A/B)

[12 24 36]
[ 8 16 24]
[ 20  80 180]
[5. 5. 5.]


In [25]:
#Mini project

marks = np.array([78, 65, 89, 91, 72, 84, 67, 95, 88, 76])
print(marks)


[78 65 89 91 72 84 67 95 88 76]


In [26]:
marks.argmax() #max marks at 7 index i.e 95

np.int64(7)

In [27]:
marks.argmin() #min marks at 1 index i.e 65

np.int64(1)

In [28]:
marks.argsort()

array([1, 6, 4, 9, 0, 5, 8, 2, 3, 7])

In [31]:
marks.nbytes

80

In [37]:
marks.sum()/marks.size

np.float64(80.5)